CREATE TABLE data(
    id serial,
    abo_non_re character varying(255)  NULL,
    abo_reside character varying(255)  NULL,
    adresse character varying(255)  NULL,
    capacite numeric  NULL,
    derniere_mise_a_jour_base character varying(255)  NULL,
    f_2h15 character varying(255)  NULL,
    f_30_mn character varying(255)  NULL,
    geo_point_2d numeric[]  NULL,
    geo_shape text  NULL,
    gml_id character varying(255)  NULL,
    gratuit integer  NULL,
    hauteur_ma integer  NULL,
    info character varying(255)  NULL,
    insee integer  NULL,
    nb_2_rm integer  NULL,
    nb_2r_el integer  NULL,
    nb_autopar integer  NULL,
    nb_covoit integer  NULL,
    nb_places integer  NULL,
    nb_pmr integer  NULL,
    nb_velo integer  NULL,
    nb_voiture integer  NULL,
    nom character varying(255)  NULL,
    nom_du_par character varying(255)  NULL,
    num_siret character varying(255)  NULL,
    places_restantes numeric  NULL,
    tarif_1h character varying(255)  NULL,
    tarif_24h integer  NULL,
    tarif_2h character varying(255)  NULL,
    tarif_3h character varying(255)  NULL,
    tarif_4h character varying(255)  NULL,
    taux_doccupation numeric  NULL,
    type_ouvra character varying(255)  NULL,
    type_usage character varying(255)  NULL,
    url character varying(255)  NULL,
    xlong numeric  NULL,
    ylat numeric  NULL,
    now timestamp with time zone  NULL,
    PRIMARY KEY(id)
)